# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e04fbe7f65abbc102321e941bd76e6650f1b2c352ba2bd223d36f1556b6304f0b107995203f2581a5d33963857858d2bd669518fa8871bd4ef135242805b3225

test:
  secret_key_base: 2ed845c6be1e44923b7a2c31396c2d4aeae807e0bb63e267387908c44b7af4f86424f37b96ae37e5538eabdbaad5d2b5db8f62ecfbe264658f3612831a4d6c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
